## A template test can assume a working Bastille installation and bootstrapped
## releases. Naming scheme follows `major-minor-release`.

bastille_template_test:
  tags:
    - bastille-template
    - bastillebsd-template
  script:
    - doas bastille version
    - doas bastille bootstrap "${CI_PROJECT_URL}"
    - doas bastille create 12-2-jail 12.2-RELEASE 10.17.89.122
    - doas bastille create 11-4-jail 11.4-RELEASE 10.17.89.114
    - doas bastille template ALL "${CI_PROJECT_NAMESPACE}"/"${CI_PROJECT_NAME}"
    - doas bastille cmd ALL 'freebsd-version'
    - doas bastille cmd ALL 'sysrc -ae'
    - doas bastille cmd ALL 'ps -auxw'
    - doas bastille pkg ALL 'audit -F'
    - doas bastille stop ALL
    - doas bastille destroy 11-4-jail
    - doas bastille destroy 12-2-jail
